services:
  # Service de base de données PostgreSQL
  postgres:
    image: postgres:14-alpine
    container_name: ineat-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ineat-network
    restart: unless-stopped

  # Service backend
  backend:
    build:
      context: ./ineat-backend
      dockerfile: Dockerfile
    container_name: ineat-backend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - postgres
    volumes:
      - ./ineat-backend:/app
      - /app/node_modules
    networks:
      - ineat-network
    restart: unless-stopped

  # Service frontend
  frontend:
    build:
      context: ./ineat-frontend
      dockerfile: Dockerfile
    container_name: ineat-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - ineat-network
    restart: unless-stopped

# Volumes
volumes:
  postgres_data:
    driver: local

# Réseau
networks:
  ineat-network:
    driver: bridge