/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as ErrorRouteRouteImport } from './routes/_error/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as ErrorNotFoundRouteImport } from './routes/_error/notFound'
import { Route as ErrorErrorRouteImport } from './routes/_error/error'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AuthCallbackRouteImport } from './routes/_auth/callback'
import { Route as AppSettingsIndexRouteImport } from './routes/app/settings/index'
import { Route as AppRecipesIndexRouteImport } from './routes/app/recipes/index'
import { Route as AppProfileIndexRouteImport } from './routes/app/profile/index'
import { Route as AppNotificationsIndexRouteImport } from './routes/app/notifications/index'
import { Route as AppInventoryIndexRouteImport } from './routes/app/inventory/index'
import { Route as AppBudgetIndexRouteImport } from './routes/app/budget/index'
import { Route as AppRecipesSuggestionsRouteImport } from './routes/app/recipes/suggestions'
import { Route as AppRecipesRecipeIdRouteImport } from './routes/app/recipes/$recipeId'
import { Route as AppInventoryScanProductRouteImport } from './routes/app/inventory/scan-product'
import { Route as AppInventoryImportProductRouteImport } from './routes/app/inventory/import-product'
import { Route as AppInventoryAddProductRouteImport } from './routes/app/inventory/add-product'
import { Route as AppInventoryAddManualRouteImport } from './routes/app/inventory/add-manual'
import { Route as AppInventoryProductIdRouteImport } from './routes/app/inventory/$productId'
import { Route as AppInventoryItemIdRouteImport } from './routes/app/inventory/$itemId'
import { Route as AppSettingsSecurityIndexRouteImport } from './routes/app/settings/security/index'
import { Route as AppSettingsPersonalInfoIndexRouteImport } from './routes/app/settings/personal-info/index'
import { Route as AppSettingsDietRestrictionsIndexRouteImport } from './routes/app/settings/diet-restrictions/index'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorRouteRoute = ErrorRouteRouteImport.update({
  id: '/_error',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const ErrorNotFoundRoute = ErrorNotFoundRouteImport.update({
  id: '/notFound',
  path: '/notFound',
  getParentRoute: () => ErrorRouteRoute,
} as any)
const ErrorErrorRoute = ErrorErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => ErrorRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRecipesIndexRoute = AppRecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProfileIndexRoute = AppProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppNotificationsIndexRoute = AppNotificationsIndexRouteImport.update({
  id: '/notifications/',
  path: '/notifications/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInventoryIndexRoute = AppInventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBudgetIndexRoute = AppBudgetIndexRouteImport.update({
  id: '/budget/',
  path: '/budget/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRecipesSuggestionsRoute = AppRecipesSuggestionsRouteImport.update({
  id: '/recipes/suggestions',
  path: '/recipes/suggestions',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRecipesRecipeIdRoute = AppRecipesRecipeIdRouteImport.update({
  id: '/recipes/$recipeId',
  path: '/recipes/$recipeId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInventoryScanProductRoute = AppInventoryScanProductRouteImport.update({
  id: '/inventory/scan-product',
  path: '/inventory/scan-product',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInventoryImportProductRoute =
  AppInventoryImportProductRouteImport.update({
    id: '/inventory/import-product',
    path: '/inventory/import-product',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppInventoryAddProductRoute = AppInventoryAddProductRouteImport.update({
  id: '/inventory/add-product',
  path: '/inventory/add-product',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInventoryAddManualRoute = AppInventoryAddManualRouteImport.update({
  id: '/inventory/add-manual',
  path: '/inventory/add-manual',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInventoryProductIdRoute = AppInventoryProductIdRouteImport.update({
  id: '/inventory/$productId',
  path: '/inventory/$productId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInventoryItemIdRoute = AppInventoryItemIdRouteImport.update({
  id: '/inventory/$itemId',
  path: '/inventory/$itemId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsSecurityIndexRoute =
  AppSettingsSecurityIndexRouteImport.update({
    id: '/settings/security/',
    path: '/settings/security/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppSettingsPersonalInfoIndexRoute =
  AppSettingsPersonalInfoIndexRouteImport.update({
    id: '/settings/personal-info/',
    path: '/settings/personal-info/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppSettingsDietRestrictionsIndexRoute =
  AppSettingsDietRestrictionsIndexRouteImport.update({
    id: '/settings/diet-restrictions/',
    path: '/settings/diet-restrictions/',
    getParentRoute: () => AppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/callback': typeof AuthCallbackRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/error': typeof ErrorErrorRoute
  '/notFound': typeof ErrorNotFoundRoute
  '/app/': typeof AppIndexRoute
  '/app/inventory/$itemId': typeof AppInventoryItemIdRoute
  '/app/inventory/$productId': typeof AppInventoryProductIdRoute
  '/app/inventory/add-manual': typeof AppInventoryAddManualRoute
  '/app/inventory/add-product': typeof AppInventoryAddProductRoute
  '/app/inventory/import-product': typeof AppInventoryImportProductRoute
  '/app/inventory/scan-product': typeof AppInventoryScanProductRoute
  '/app/recipes/$recipeId': typeof AppRecipesRecipeIdRoute
  '/app/recipes/suggestions': typeof AppRecipesSuggestionsRoute
  '/app/budget': typeof AppBudgetIndexRoute
  '/app/inventory': typeof AppInventoryIndexRoute
  '/app/notifications': typeof AppNotificationsIndexRoute
  '/app/profile': typeof AppProfileIndexRoute
  '/app/recipes': typeof AppRecipesIndexRoute
  '/app/settings': typeof AppSettingsIndexRoute
  '/app/settings/diet-restrictions': typeof AppSettingsDietRestrictionsIndexRoute
  '/app/settings/personal-info': typeof AppSettingsPersonalInfoIndexRoute
  '/app/settings/security': typeof AppSettingsSecurityIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback': typeof AuthCallbackRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/error': typeof ErrorErrorRoute
  '/notFound': typeof ErrorNotFoundRoute
  '/app': typeof AppIndexRoute
  '/app/inventory/$itemId': typeof AppInventoryItemIdRoute
  '/app/inventory/$productId': typeof AppInventoryProductIdRoute
  '/app/inventory/add-manual': typeof AppInventoryAddManualRoute
  '/app/inventory/add-product': typeof AppInventoryAddProductRoute
  '/app/inventory/import-product': typeof AppInventoryImportProductRoute
  '/app/inventory/scan-product': typeof AppInventoryScanProductRoute
  '/app/recipes/$recipeId': typeof AppRecipesRecipeIdRoute
  '/app/recipes/suggestions': typeof AppRecipesSuggestionsRoute
  '/app/budget': typeof AppBudgetIndexRoute
  '/app/inventory': typeof AppInventoryIndexRoute
  '/app/notifications': typeof AppNotificationsIndexRoute
  '/app/profile': typeof AppProfileIndexRoute
  '/app/recipes': typeof AppRecipesIndexRoute
  '/app/settings': typeof AppSettingsIndexRoute
  '/app/settings/diet-restrictions': typeof AppSettingsDietRestrictionsIndexRoute
  '/app/settings/personal-info': typeof AppSettingsPersonalInfoIndexRoute
  '/app/settings/security': typeof AppSettingsSecurityIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_error': typeof ErrorRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/_auth/callback': typeof AuthCallbackRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_error/error': typeof ErrorErrorRoute
  '/_error/notFound': typeof ErrorNotFoundRoute
  '/app/': typeof AppIndexRoute
  '/app/inventory/$itemId': typeof AppInventoryItemIdRoute
  '/app/inventory/$productId': typeof AppInventoryProductIdRoute
  '/app/inventory/add-manual': typeof AppInventoryAddManualRoute
  '/app/inventory/add-product': typeof AppInventoryAddProductRoute
  '/app/inventory/import-product': typeof AppInventoryImportProductRoute
  '/app/inventory/scan-product': typeof AppInventoryScanProductRoute
  '/app/recipes/$recipeId': typeof AppRecipesRecipeIdRoute
  '/app/recipes/suggestions': typeof AppRecipesSuggestionsRoute
  '/app/budget/': typeof AppBudgetIndexRoute
  '/app/inventory/': typeof AppInventoryIndexRoute
  '/app/notifications/': typeof AppNotificationsIndexRoute
  '/app/profile/': typeof AppProfileIndexRoute
  '/app/recipes/': typeof AppRecipesIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/settings/diet-restrictions/': typeof AppSettingsDietRestrictionsIndexRoute
  '/app/settings/personal-info/': typeof AppSettingsPersonalInfoIndexRoute
  '/app/settings/security/': typeof AppSettingsSecurityIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/callback'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/error'
    | '/notFound'
    | '/app/'
    | '/app/inventory/$itemId'
    | '/app/inventory/$productId'
    | '/app/inventory/add-manual'
    | '/app/inventory/add-product'
    | '/app/inventory/import-product'
    | '/app/inventory/scan-product'
    | '/app/recipes/$recipeId'
    | '/app/recipes/suggestions'
    | '/app/budget'
    | '/app/inventory'
    | '/app/notifications'
    | '/app/profile'
    | '/app/recipes'
    | '/app/settings'
    | '/app/settings/diet-restrictions'
    | '/app/settings/personal-info'
    | '/app/settings/security'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callback'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/error'
    | '/notFound'
    | '/app'
    | '/app/inventory/$itemId'
    | '/app/inventory/$productId'
    | '/app/inventory/add-manual'
    | '/app/inventory/add-product'
    | '/app/inventory/import-product'
    | '/app/inventory/scan-product'
    | '/app/recipes/$recipeId'
    | '/app/recipes/suggestions'
    | '/app/budget'
    | '/app/inventory'
    | '/app/notifications'
    | '/app/profile'
    | '/app/recipes'
    | '/app/settings'
    | '/app/settings/diet-restrictions'
    | '/app/settings/personal-info'
    | '/app/settings/security'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_error'
    | '/app'
    | '/_auth/callback'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_error/error'
    | '/_error/notFound'
    | '/app/'
    | '/app/inventory/$itemId'
    | '/app/inventory/$productId'
    | '/app/inventory/add-manual'
    | '/app/inventory/add-product'
    | '/app/inventory/import-product'
    | '/app/inventory/scan-product'
    | '/app/recipes/$recipeId'
    | '/app/recipes/suggestions'
    | '/app/budget/'
    | '/app/inventory/'
    | '/app/notifications/'
    | '/app/profile/'
    | '/app/recipes/'
    | '/app/settings/'
    | '/app/settings/diet-restrictions/'
    | '/app/settings/personal-info/'
    | '/app/settings/security/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ErrorRouteRoute: typeof ErrorRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_error': {
      id: '/_error'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ErrorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_error/notFound': {
      id: '/_error/notFound'
      path: '/notFound'
      fullPath: '/notFound'
      preLoaderRoute: typeof ErrorNotFoundRouteImport
      parentRoute: typeof ErrorRouteRoute
    }
    '/_error/error': {
      id: '/_error/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorErrorRouteImport
      parentRoute: typeof ErrorRouteRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/callback': {
      id: '/_auth/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/app/settings/': {
      id: '/app/settings/'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/recipes/': {
      id: '/app/recipes/'
      path: '/recipes'
      fullPath: '/app/recipes'
      preLoaderRoute: typeof AppRecipesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/profile/': {
      id: '/app/profile/'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/notifications/': {
      id: '/app/notifications/'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/inventory/': {
      id: '/app/inventory/'
      path: '/inventory'
      fullPath: '/app/inventory'
      preLoaderRoute: typeof AppInventoryIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/budget/': {
      id: '/app/budget/'
      path: '/budget'
      fullPath: '/app/budget'
      preLoaderRoute: typeof AppBudgetIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/recipes/suggestions': {
      id: '/app/recipes/suggestions'
      path: '/recipes/suggestions'
      fullPath: '/app/recipes/suggestions'
      preLoaderRoute: typeof AppRecipesSuggestionsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/recipes/$recipeId': {
      id: '/app/recipes/$recipeId'
      path: '/recipes/$recipeId'
      fullPath: '/app/recipes/$recipeId'
      preLoaderRoute: typeof AppRecipesRecipeIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/inventory/scan-product': {
      id: '/app/inventory/scan-product'
      path: '/inventory/scan-product'
      fullPath: '/app/inventory/scan-product'
      preLoaderRoute: typeof AppInventoryScanProductRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/inventory/import-product': {
      id: '/app/inventory/import-product'
      path: '/inventory/import-product'
      fullPath: '/app/inventory/import-product'
      preLoaderRoute: typeof AppInventoryImportProductRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/inventory/add-product': {
      id: '/app/inventory/add-product'
      path: '/inventory/add-product'
      fullPath: '/app/inventory/add-product'
      preLoaderRoute: typeof AppInventoryAddProductRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/inventory/add-manual': {
      id: '/app/inventory/add-manual'
      path: '/inventory/add-manual'
      fullPath: '/app/inventory/add-manual'
      preLoaderRoute: typeof AppInventoryAddManualRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/inventory/$productId': {
      id: '/app/inventory/$productId'
      path: '/inventory/$productId'
      fullPath: '/app/inventory/$productId'
      preLoaderRoute: typeof AppInventoryProductIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/inventory/$itemId': {
      id: '/app/inventory/$itemId'
      path: '/inventory/$itemId'
      fullPath: '/app/inventory/$itemId'
      preLoaderRoute: typeof AppInventoryItemIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings/security/': {
      id: '/app/settings/security/'
      path: '/settings/security'
      fullPath: '/app/settings/security'
      preLoaderRoute: typeof AppSettingsSecurityIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings/personal-info/': {
      id: '/app/settings/personal-info/'
      path: '/settings/personal-info'
      fullPath: '/app/settings/personal-info'
      preLoaderRoute: typeof AppSettingsPersonalInfoIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings/diet-restrictions/': {
      id: '/app/settings/diet-restrictions/'
      path: '/settings/diet-restrictions'
      fullPath: '/app/settings/diet-restrictions'
      preLoaderRoute: typeof AppSettingsDietRestrictionsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface ErrorRouteRouteChildren {
  ErrorErrorRoute: typeof ErrorErrorRoute
  ErrorNotFoundRoute: typeof ErrorNotFoundRoute
}

const ErrorRouteRouteChildren: ErrorRouteRouteChildren = {
  ErrorErrorRoute: ErrorErrorRoute,
  ErrorNotFoundRoute: ErrorNotFoundRoute,
}

const ErrorRouteRouteWithChildren = ErrorRouteRoute._addFileChildren(
  ErrorRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppInventoryItemIdRoute: typeof AppInventoryItemIdRoute
  AppInventoryProductIdRoute: typeof AppInventoryProductIdRoute
  AppInventoryAddManualRoute: typeof AppInventoryAddManualRoute
  AppInventoryAddProductRoute: typeof AppInventoryAddProductRoute
  AppInventoryImportProductRoute: typeof AppInventoryImportProductRoute
  AppInventoryScanProductRoute: typeof AppInventoryScanProductRoute
  AppRecipesRecipeIdRoute: typeof AppRecipesRecipeIdRoute
  AppRecipesSuggestionsRoute: typeof AppRecipesSuggestionsRoute
  AppBudgetIndexRoute: typeof AppBudgetIndexRoute
  AppInventoryIndexRoute: typeof AppInventoryIndexRoute
  AppNotificationsIndexRoute: typeof AppNotificationsIndexRoute
  AppProfileIndexRoute: typeof AppProfileIndexRoute
  AppRecipesIndexRoute: typeof AppRecipesIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppSettingsDietRestrictionsIndexRoute: typeof AppSettingsDietRestrictionsIndexRoute
  AppSettingsPersonalInfoIndexRoute: typeof AppSettingsPersonalInfoIndexRoute
  AppSettingsSecurityIndexRoute: typeof AppSettingsSecurityIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppInventoryItemIdRoute: AppInventoryItemIdRoute,
  AppInventoryProductIdRoute: AppInventoryProductIdRoute,
  AppInventoryAddManualRoute: AppInventoryAddManualRoute,
  AppInventoryAddProductRoute: AppInventoryAddProductRoute,
  AppInventoryImportProductRoute: AppInventoryImportProductRoute,
  AppInventoryScanProductRoute: AppInventoryScanProductRoute,
  AppRecipesRecipeIdRoute: AppRecipesRecipeIdRoute,
  AppRecipesSuggestionsRoute: AppRecipesSuggestionsRoute,
  AppBudgetIndexRoute: AppBudgetIndexRoute,
  AppInventoryIndexRoute: AppInventoryIndexRoute,
  AppNotificationsIndexRoute: AppNotificationsIndexRoute,
  AppProfileIndexRoute: AppProfileIndexRoute,
  AppRecipesIndexRoute: AppRecipesIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppSettingsDietRestrictionsIndexRoute: AppSettingsDietRestrictionsIndexRoute,
  AppSettingsPersonalInfoIndexRoute: AppSettingsPersonalInfoIndexRoute,
  AppSettingsSecurityIndexRoute: AppSettingsSecurityIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ErrorRouteRoute: ErrorRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
