[build]
builder = "nixpacks"
nixpacksConfigPath = "nixpacks.toml"
buildCommand = "pnpm run build"

[deploy]
startCommand = "caddy run --config Caddyfile --adapter caddyfile"
healthcheckPath = "/health"
healthcheckTimeout = 120
